{
 "title": "Internet Monitoring",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Download",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "download_speed_bps{}" }
   ]
  },
  {
   "title": "Upload",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "upload_speed_bps{}" }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ping_ms{}" }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    { "expr": "download_speed_bps{}", "legendFormat": "Download" },
    { "expr": "upload_speed_bps{}", "legendFormat": "Upload" }
   ]
  }
 ]
}